// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgzSEjIx56JW0S8rrB8h_5istL387sZoU',
    appId: '1:861375971689:web:1093da7b5205d60847bdf8',
    messagingSenderId: '861375971689',
    projectId: 'books-ae871',
    authDomain: 'books-ae871.firebaseapp.com',
    storageBucket: 'books-ae871.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAms2gndtsZqMN4OVviXQ1pEORXYXvSgEw',
    appId: '1:861375971689:android:2331a54e874a831247bdf8',
    messagingSenderId: '861375971689',
    projectId: 'books-ae871',
    storageBucket: 'books-ae871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp53R7eLaRETaX6s8XrXjngyllvRMBEW0',
    appId: '1:861375971689:ios:a5f1c63fe98311d347bdf8',
    messagingSenderId: '861375971689',
    projectId: 'books-ae871',
    storageBucket: 'books-ae871.firebasestorage.app',
    iosBundleId: 'com.bookbase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp53R7eLaRETaX6s8XrXjngyllvRMBEW0',
    appId: '1:861375971689:ios:a5f1c63fe98311d347bdf8',
    messagingSenderId: '861375971689',
    projectId: 'books-ae871',
    storageBucket: 'books-ae871.firebasestorage.app',
    iosBundleId: 'com.bookbase.app',
  );
}
